"""
Vox Prompts 模块 - 多平台文案 Prompt 模板
"""

from .xiaohongshu import XIAOHONGSHU_PROMPT, XIAOHONGSHU_ANALYSIS_PROMPT
from .tiktok import TIKTOK_PROMPT, TIKTOK_ANALYSIS_PROMPT
from .official import OFFICIAL_PROMPT, OFFICIAL_ANALYSIS_PROMPT
from .friend import FRIEND_CIRCLE_PROMPT, FRIEND_CIRCLE_ANALYSIS_PROMPT

__all__ = [
    "XIAOHONGSHU_PROMPT",
    "XIAOHONGSHU_ANALYSIS_PROMPT",
    "TIKTOK_PROMPT",
    "TIKTOK_ANALYSIS_PROMPT",
    "OFFICIAL_PROMPT",
    "OFFICIAL_ANALYSIS_PROMPT",
    "FRIEND_CIRCLE_PROMPT",
    "FRIEND_CIRCLE_ANALYSIS_PROMPT",
]
